apiVersion: v1
kind: Service
metadata:
  name: devops-service
spec:
  type: NodePort   # 🔥 better for Minikube
  selector:
    app: devops-app
  ports:
    - port: 80
      targetPort: 8080   # ✅ FIXED
      nodePort: 30007    # optional